ALTER TYPE "BIKEventType" ADD VALUE 'RENDER_PING';
ALTER TYPE "BIKEventType" ADD VALUE 'CLIENT_ERROR';

ALTER TABLE "bik_events"
  ADD COLUMN "isRouteChange" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "visitorIdSource" TEXT,
  ADD COLUMN "errorCode" TEXT;

ALTER TABLE "bik_rollup_minute"
  ADD COLUMN "pageviewsRaw" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "routeChangePageviews" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "renderPings" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "dedupedPageviews" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "clientErrorCount" INTEGER NOT NULL DEFAULT 0;
